name: example
description: A new Flutter project.

publish_to: "none"

version: 3.0.1+52

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  toastification:
    path: ../
  dart_style: ^3.0.1
  flutter_svg: ^2.0.6
  font_awesome_flutter: ^10.4.0
  flutter_sticky_header: ^0.8.0
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  responsive_framework: ^0.2.0
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^3.0.0
  iconsax_flutter: ^1.0.0
  url_launcher: ^6.1.12
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_spinkit: ^5.2.0
  http: ^1.1.0
  flex_color_picker: ^3.7.0
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  path_provider: ^2.1.4
  path: ^1.9.0
  sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.4
  freezed: ^3.0.6
  drift_dev: ^2.21.0

flutter:
  uses-material-design: true

  fonts:
    - family: PlusJakartaDisplay
      fonts:
        - asset: fonts/PlusJakartaDisplay-Regular.otf
          weight: 400
        - asset: fonts/PlusJakartaDisplay-Medium.otf
          weight: 500
        - asset: fonts/PlusJakartaDisplay-Bold.otf
          weight: 700

  assets:
    - assets/img/
